# Generated by Django 4.1.2 on 2022-10-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Autor', models.CharField(max_length=50)),
            ],
        ),
    ]
